/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef JDKSWITCHER_PRIVATE_H
#define JDKSWITCHER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"5.0.0.1"
#define VER_MAJOR	5
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	1
#define COMPANY_NAME	"Hileb"
#define FILE_VERSION	"5.0.0.1"
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	"JDKSwitcher"
#define LEGAL_COPYRIGHT	"Hileb"
#define LEGAL_TRADEMARKS	"Hileb"
#define ORIGINAL_FILENAME	"JDKSwitcher"
#define PRODUCT_NAME	"JDKSwitcher"
#define PRODUCT_VERSION	"5.0.0.1"

#endif /*JDKSWITCHER_PRIVATE_H*/
